### ISSUE TITLE
1D arrays for matrices

### ISSUE THREAD

**Issue by JulianDicken** [dicksonlaw583/gmlinear2#3]
As far as I can tell matrices should be implemented as 1D arrays since GameMaker seems to be using 1D arrays for its internal matrix operations. 
I guess 2D arrays make these easier to work on but a wrapper method would be an easy workaround for this, i.e : 
```js
mat = r22(
    0, 1,
    2, 3,
);
mat.at(0,0)
```

**Comment by dicksonlaw583** [comment]
`r22` and the rest of the GMLinear 2 matrix helpers work as 2D arrays, not structs, so they cannot have methods.

Also, the so-called "matrices" in the GML built-in `matrix_*` functions are always 4x4 matrices, and that assumption allows them to be implemented as 1D arrays. But GMLinear 2 matrices are general mxn matrices, so there is no chance of them being able to be represented uniquely as 1D arrays (e.g. an 8-entry 1D array could be interpreted as a 1x8, 2x4, 4x2, or 8x1 matrix, and there would be no way to tell between them). I can add a helper for converting `r44` specifically, but no more than that.

**Comment by dicksonlaw583** [comment]
I have added a side branch that implements the conversion functions `r44_to_matrix(M, <MatOut>)` and `matrix_to_r44(MatIn, <Mout>)`, scheduled for the next major release.

https://github.com/dicksonlaw583/gmlinear2/tree/dev-gml-matrix
